package com.rehi.SparkCore

//RECORDS WOULD BE LIKE: id<Unique>,Name<Unique>,Designation,Department,Salary,some aggregation in salary!
import org.apache.spark.SparkConf
import org.apache.spark.SparkContext
import org.apache.spark.sql.SQLContext
  import org.apache.hadoop.conf.Configuration;
import org.apache.hadoop.fs.FileSystem;
import org.apache.hadoop.fs.Path;
import java.io.PrintWriter;

class csvWriteHdfs {


def main(args : Array[String]) {
println( "Trying to write to HDFS..." )

//AS NO SCALA IN CLUSTER HAD TO RUN IN SPARK-SHELL JUST RUN EACH STEP ONE BY ONE AND OMIT TRY
val conf1 = new Configuration()
val fs= FileSystem.get(conf1)

//locate core-site.xml
//choose the any of the xml from the list 
//run: cat .....PATHofXML..../core-site.xml | grep -A2 fs.defaultFS
//this will give the default value and use it to set conf..


conf1.set("fs.defaultFS", "hdfs://nameNodePath")

val output = fs.create(new Path("/user/nsouser/test/imptest/AutoGeneratedHuge.csv"))
val pw = new PrintWriter(output)
try {
  val autoStart = 10000
    var annualSal = 10000.toLong
    var Factor = 2000.toLong
    for(i<- 1 to 400000375){
        if(i<= 100000000){
              var salFactor = annualSal - Factor
              if(i <= 25000000){
                  var createString = autoStart+i+", Name"+i+",Associate Software Engineer, BIGDATA ANALYSTICS ,"+annualSal+","+ salFactor
                  pw.write(createString)
                  pw.write("\n")
                  // println(createString)  
                  }
              else if(i> 25000000 && i<=50000000){
                  var createString = autoStart+i+", Name"+i+",Associate Software Engineer, UI DEVELOPMENT ,"+annualSal+","+ salFactor
                  pw.write(createString)
                  pw.write("\n")
                  // println(createString)  
                  }
              else if(i> 50000000 && i<=75000000){
                  var createString = autoStart+i+", Name"+i+",Associate Software Engineer, PRODUCTION SUPPORT ,"+annualSal+","+ salFactor
                  pw.write(createString)
                  pw.write("\n")
                  // println(createString)  
                  }
              else{
                  var createString = autoStart+i+", Name"+i+",Associate Software Engineer, JAVA ,"+annualSal+","+ salFactor
                  pw.write(createString)
                  pw.write("\n")
                  // println(createString)  
                }  
        }
      
//      pw.write(createString)
      
      
      else if(i> 100000000 && i<=200000000){
        val annualSal1 = annualSal+annualSal
        var salFactor1 = annualSal1 - Factor
          if(i <= 125000000){
                  var createString = autoStart+i+", Name"+i+",Software Engineer, BIGDATA ANALYSTICS ,"+annualSal1+","+ salFactor1
                  pw.write(createString)
                  pw.write("\n")
                  // println(createString)  
                  }
              else if(i> 125000000 && i<=150000000){
                  var createString = autoStart+i+", Name"+i+",Software Engineer, UI DEVELOPMENT ,"+annualSal1+","+ salFactor1
                  pw.write(createString)
                  pw.write("\n")
                  // println(createString)  
                  }
              else if(i> 150000000 && i<=175000000){
                  var createString = autoStart+i+", Name"+i+",Software Engineer, PRODUCTION SUPPORT ,"+annualSal1+","+ salFactor1
                  pw.write(createString)
                  pw.write("\n")
                  // println(createString)  
                  }
              else{
                  var createString = autoStart+i+", Name"+i+",Software Engineer, JAVA ,"+annualSal1+","+ salFactor1
                  pw.write(createString)
                  // println(createString)
                  pw.write("\n")  
                }  
//        pw.write(createString)
      }
      
      else if(i> 200000000 && i<=300000000){
        val annualSal1 = annualSal+annualSal+annualSal
        val salFactor1 = annualSal1 - Factor
        if(i <= 22500000){
                  var createString = autoStart+i+", Name"+i+",Senior Engineer, BIGDATA ANALYSTICS ,"+annualSal1+","+ salFactor1
                  pw.write(createString)
                  pw.write("\n")
                  // println(createString)  
                  }
              else if(i> 225000000 && i<=250000000){
                  var createString = autoStart+i+", Name"+i+",Senior Engineer, UI DEVELOPMENT ,"+annualSal1+","+ salFactor1
                  pw.write(createString)
                  pw.write("\n")
                  // println(createString)  
                  }
              else if(i> 250000000 && i<=275000000){
                  var createString = autoStart+i+", Name"+i+",Senior Engineer, PRODUCTION SUPPORT ,"+annualSal1+","+ salFactor1
                  pw.write(createString)
                  pw.write("\n")
                  // println(createString)  
                  }
              else{
                  var createString = autoStart+i+", Name"+i+",Senior Engineer, JAVA ,"+annualSal1+","+ salFactor1
                  pw.write(createString)
                  pw.write("\n")
                  // println(createString)  
                }  
//      pw.write(createString)
      
      }
      
      
      else if(i> 300000000 && i<=400000000){
        val annualSal1 = annualSal+annualSal+annualSal+annualSal
        val salFactor1 = annualSal1 - Factor
        if(i <= 32500000){
                  var createString = autoStart+i+", Name"+i+",Tech Lead, BIGDATA ANALYSTICS ,"+annualSal1+","+ salFactor1
                  pw.write(createString)
                  pw.write("\n")
                  // println(createString)  
                  }
              else if(i> 325000000 && i<=350000000){
                  var createString = autoStart+i+", Name"+i+",Tech Lead, UI DEVELOPMENT ,"+annualSal1+","+ salFactor1
                  pw.write(createString)
                  pw.write("\n")
                  // println(createString)  
                  }
              else if(i> 350000000 && i<=375000000){
                  var createString = autoStart+i+", Name"+i+",Tech Lead, PRODUCTION SUPPORT ,"+annualSal1+","+ salFactor1
                  pw.write(createString)
                  pw.write("\n")
                  // println(createString)  
                  }
              else{
                  var createString = autoStart+i+", Name"+i+",Tech Lead, JAVA ,"+annualSal1+","+ salFactor1
                  pw.write(createString)
                  pw.write("\n")
                  // println(createString)  
                }   
//      pw.write(createString)
      
      }
        
      else{
        val annualSal1 = annualSal+annualSal+annualSal+annualSal+annualSal
        val salFactor1 = annualSal1 - Factor
        if(i %2==0){
                  var createString = autoStart+i+", Name"+i+",MANAGER, OFFSHORE ,"+annualSal1+","+ salFactor1
                  pw.write(createString)
                  pw.write("\n")
                  // println(createString)  
                  }
              else{
                  var createString = autoStart+i+", Name"+i+",MANAGER, ONSHORE ,"+annualSal1+","+ salFactor1
                  pw.write(createString)
                  pw.write("\n")
                  // println(createString)  
                }   
//      pw.write(createString)
      
      }
        
        
    }
}
finally {
    pw.close()
}
print("DONE! FILE CREATED!")
}

}
